[versions]
bcprov-jdk18on = "1.80"
commons-configuration2 = "2.13.0"
commons-validator = "1.10.1"
device-detector = "1.0.10"
displaytag = "3.5.0"
expressly = "6.0.0"
foojay = "1.0.0"
hibernate-validator = "9.1.0.Final"
kotlin = "2.3.0"
kotlin-logging-jvm = "7.0.14"
jackson = "2.20.1"
jakarta-annotation-api = "3.0.0"
jakarta-validation-api = "3.1.1"
jasypt-hibernate5 = "1.9.3"
jjwt = "0.12.6"
jsonschema2pojo = "1.2.2"
junit = "6.0.2"
junit-platform-launcher = "6.0.2"
logback = "1.5.24"
logbackext-lib = "1.0.7"
lombok = "8.18.42"
mockk = "1.14.5"
ms-base-lib = "0.0.3"
ms-ex-lib = "0.0.4"
ms-reqresp-lib = "0.0.15"
oro = "2.0.8"
release = "3.1.0"
slf4j-api = "2.0.17"
sonarqube = "7.2.2.6593"
spotless = "8.1.0"
spring-boot = "4.0.1"
spring-dependency-management = "1.1.7"
springdoc-openapi = "3.0.1"
springmockk = "5.0.1"
struts2 = "7.0.3"
swagger-annotations = "2.2.41"
taglibs-datetime = "1.0.1"
taglibs-string = "1.1.0"
task-tree = "4.0.1"

[libraries]
bcprov-jdk18on = { module = "org.bouncycastle:bcprov-jdk18on", version.ref = "bcprov-jdk18on" }
commons-configuration2 = { module = "org.apache.commons:commons-configuration2", version.ref = "commons-configuration2" }
commons-validator = { module = "commons-validator:commons-validator", version.ref = "commons-validator" }
device-detector = { module = "io.github.mngsk:device-detector", version.ref = "device-detector" }
displaytag = { module = "com.github.hazendaz:displaytag", version.ref = "displaytag" }
expressly = { module = "org.glassfish.expressly:expressly", version.ref = "expressly" }
hibernate-validator = { module = "org.hibernate.validator:hibernate-validator", version.ref = "hibernate-validator" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jakarta-annotation-api = { module = "jakarta.annotation:jakarta.annotation-api", version.ref = "jakarta-annotation-api" }
jakarta-validation-api = { module = "jakarta.validation:jakarta.validation-api", version.ref = "jakarta-validation-api" }
jasypt-hibernate5 = { module = "org.jasypt:jasypt-hibernate5", version.ref = "jasypt-hibernate5" }
jjwt-api = { module = "io.jsonwebtoken:jjwt-api", version.ref = "jjwt" }
jjwt-impl = { module = "io.jsonwebtoken:jjwt-impl", version.ref = "jjwt" }
jjwt-jackson = { module = "io.jsonwebtoken:jjwt-jackson", version.ref = "jjwt" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform-launcher" }
kotlin-logging-jvm = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlin-logging-jvm" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logback-core = { module = "ch.qos.logback:logback-core", version.ref = "logback" }
logbackext-lib = { module = "com.rubensgomes:logbackext-lib", version.ref = "logbackext-lib" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
ms-base-lib = { module = "com.rubensgomes:ms-base-lib", version.ref = "ms-base-lib" }
ms-ex-lib = { module = "com.rubensgomes:ms-ex-lib", version.ref = "ms-ex-lib" }
ms-reqresp-lib = { module = "com.rubensgomes:ms-reqresp-lib", version.ref = "ms-reqresp-lib" }
oro = { module = "oro:oro", version.ref = "oro" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j-api" }
springdoc-openapi-starter-webmvc-ui = {module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc-openapi"}
springmockk = { module = "com.ninja-squad:springmockk", version.ref = "springmockk" }
swagger-annotations = { module = "io.swagger.core.v3:swagger-annotations", version.ref = "swagger-annotations" }
taglibs-datetime = { module = "taglibs:datetime", version.ref = "taglibs-datetime" }
taglibs-string = { module = "taglibs:string", version.ref = "taglibs-string" }

[bundles]
jakarta-bean-validator = ["jakarta-validation-api", "expressly", "hibernate-validator"]
junit-jupiter = ["junit-jupiter-api", "junit-jupiter-engine"]
kotlin-junit5 = ["mockk", "kotlin-test-junit5", "junit-jupiter-engine"]
logback = ["logback-classic", "logback-core"]

[plugins]
fooja = { id = "org.gradle.toolchains.foojay-resolver-convention", version.ref = "foojay" }
jsonschema2pojo = { id = "org.jsonschema2pojo", version.ref = "jsonschema2pojo" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }
release = { id = "net.researchgate.release", version.ref = "release" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
task-tree = { id = "com.dorongold.task-tree", version.ref = "task-tree" }
